import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans min-h-full w-full"><Provider>{children}</Provider></body>
    </html>
  );
}
